### ISSUE TITLE
请问训练的设置

### ISSUE THREAD

**Issue by luoqan** [Instinct323/wiou#4]
请问训练时的学习率、优化器是怎么设置的呢？

**Comment by luoqan** [comment]
您好，我现在有个问题，就是我把wiou加到mmdetection中的yolov5之后，采用线性变化的初始学习率0.0001的sgd优化器，但loss几乎不变化，学习率调大后就loss变nan，其它loss权重那些就和ciou loss是一样设置的。您知道怎么解决吗？如能指点一下非常感谢

**Comment by Instinct323** [comment]
你应该在充分了解Wise-IoU、YOLOv5之后，检查你的代码复现，比方说置信度损失 (与IoU损失关联) 的计算。网上的代码复现并不一定可靠，请自行甄别




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Instinct323/wiou"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月7日(星期四) 中午11:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Instinct323/wiou] 请问训练的设置 (Issue #4)





 
您好，我现在有个问题，就是我把wiou加到mmdetection中的yolov5之后，采用线性变化的初始学习率0.0001的sgd优化器，但loss几乎不变化，学习率调大后就loss变nan，其它loss权重那些就和ciou loss是一样设置的。您知道怎么解决吗？如能指点一下非常感谢
